### ISSUE TITLE
Adding more syntax highlighting

### ISSUE THREAD

**Issue by devMYC** [denoland/deno_blog#15]
It seems that `gfm` has turned on syntax highlighting for JavaScript, Markdown, and HTML by default. And I saw that syntax highlighting for C is also supported by this repo.

https://github.com/denoland/deno_blog/blob/a4772ab02c4c9b866c1b6717a88a3befe743fbac/deps.ts#L33

Is there a preferred way to support other languages?

**Comment by bartlomieju** [comment]
Currently there's no options, we should add a new key to `BlogSettings` interface to configure that

**Comment by yidingww** [comment]
@devMYC You can directly import the additional prismjs components/plugins to your actual blog project main.js/ts file, and it will work.

For me, I created a prismjs-extensions.ts file like this
```ts
import "https://esm.sh/prismjs@1.27.0/components/prism-typescript";
import "https://esm.sh/prismjs@1.27.0/components/prism-ruby";
import "https://esm.sh/prismjs@1.27.0/components/prism-python";
import "https://esm.sh/prismjs@1.27.0/components/prism-go";
```
Then in my `main.ts` i just import the bucket over above the `blog({...})`, it will just work
```ts
import "./prismjs-extensions.ts";

blog({
  ...
})
```

**Comment by zhenfeng-zhu** [comment]
@yidingww awesome, it's ok for me.

**Comment by sigmaSd** [comment]
I tried `import "https://esm.sh/prismjs@1.27.0/components/prism-rust?"` but it fails with
```
error: Uncaught ReferenceError: Prism is not defined
    at https://esm.sh/v99/prismjs@1.27.0/deno/components/prism-rust.js:2:3014
    at https://esm.sh/v99/prismjs@1.27.0/deno/components/prism-rust.js:2:203
    at https://esm.sh/v99/prismjs@1.27.0/deno/components/prism-rust.js:2:3031```

**Comment by kyeotic** [comment]
Is there any way to change the prism theme?
