### ISSUE TITLE
Following Getting Started Fails with error: Import assertions are deprecated.

### ISSUE THREAD

**Issue by tdharris** [denoland/deno_blog#154]
Following the [Getting Started](https://github.com/denoland/deno_blog#getting-started) section fails with newer Deno, tried with latest [Deno v2.0.3](https://github.com/denoland/deno/releases/tag/v2.0.3):

```console
❯ deno run -r --allow-read --allow-write https://deno.land/x/blog/init.ts .
```

```console
❯ deno task dev
Task dev deno run --allow-net --allow-read --allow-env --watch main.tsx --dev
Watcher Process started.
error: Import assertions are deprecated. Use `with` keyword, instead of 'assert' keyword.

import emojis from "./all.json" assert { type: "json" };

  at https://deno.land/x/emoji@0.3.0/emoji.ts:2:1

Watcher Process failed. Restarting on file change...
```

**Comment by tdharris** [comment]
Fixed by [denosaurs/emoji v0.3.1](https://github.com/denosaurs/emoji/releases/tag/0.3.1) as mentioned in #151.

**Comment by willpuckett** [comment]
updating [deps.ts](https://github.com/denoland/deno_blog/blob/d251507ac9fe61077f29cc8190c64d0f344ea473/deps.ts#L17) gfm import to 0.10.0 seems to resolve this.

**Comment by willpuckett** [comment]
You can import map till it's resolved...

```
 "imports": {
    "https://deno.land/x/gfm@0.2.5/mod.ts": "jsr:@deno/gfm"
  }
```

**Comment by tdharris** [comment]
That fixes it! Thank you.

**Comment by JLCarveth** [comment]
I am still getting this error.

```
➜  tmp mkdir testblog && cd testblog
➜  testblog deno run -r --allow-read --allow-write https://deno.land/x/blog/init.ts .
Warning Implicitly using latest version (0.7.0) for https://deno.land/x/blog/init.ts
Initializing blog in /home/jlcarveth/tmp/testblog...
Blog initialized, run `deno task dev` to get started.
➜  testblog deno task dev
Task dev deno run --allow-net --allow-read --allow-env --watch main.tsx --dev
Watcher Process started.
error: Import assertions are deprecated. Use `with` keyword, instead of 'assert' keyword.

import emojis from "./all.json" assert { type: "json" };

  at https://deno.land/x/emoji@0.3.0/emoji.ts:2:1

Watcher Process failed. Restarting on file change...

```

**Comment by willpuckett** [comment]
You're using 0.7.0 which was released on 7/6/2023... in your deno.json/jsonc point the project to head ie something like 

```
  "imports": {
    "deno_blog/": "https://pax.deno.dev/denoland/deno_blog/",

```

**Comment by JLCarveth** [comment]
according to https://github.com/denoland/deno_blog/releases 0.7.0 is the latest. If this is not the case my apologies

**Comment by willpuckett** [comment]
Apologies on my part. 0.7.0 *is* the latest release, but it's so old it doesn't include the fixes for deno 2.0. You'll need to use to git repo's mian branch directly. The release won't help you.
